NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

from newsportal.views import PostsList, PostDetail, PostSearch, subscribe
from sign.views import AccountView, set_user_group_to_common

# from newsportal.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('newsportal.urls')),
    path('articles/', include('newsportal.urls_articles')),
    path('search/', PostSearch.as_view(), name='post_search'),
    path('', PostsList.as_view()),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/', AccountView.as_view()),
    path('common/', set_user_group_to_common),
    path('subscribe/', subscribe),
    #path('<int:pk>/', PostDetail.as_view(), name='post_detail'),
    #path('hello/', IndexView.as_view())
]

NewsPaper/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView

from .views import BaseRegisterView, set_user_group_author, activate

urlpatterns = [
    path('', RedirectView.as_view(url='/sign/login/')),
    path('login/',
         LoginView.as_view(template_name='sign/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name='sign/logout.html'),
         name='logout'),
    path('signup/',
         BaseRegisterView.as_view(template_name='sign/signup.html'),
         name='signup'),
    path('promote/', set_user_group_author, name='set_user_group_author'),
    path('activate/<uidb64>/<token>', activate, name='activate')

]

NewsPaper/newsportal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.cache import cache

news = 'NW'
article = 'AR'
TYPES = [
    (news, 'News'),
    (article, 'Article')
]


class Author(models.Model):
    author_rating = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}'

    def update_rating(self):
        self.author_rating = 0
        for i in self.post_set.values('post_rating'):
            self.author_rating += i['post_rating'] * 3
        for i in self.user.comment_set.values('comment_rating'):
            self.author_rating += i['comment_rating']
        for i in self.post_set.all():
            for j in i.comment_set.values('comment_rating'):
                self.author_rating += j['comment_rating']

        self.save()


class Category(models.Model):
    category = models.CharField(unique=True, max_length=100)
    users = models.ManyToManyField(User, through='Subscribers', blank=True)

    def __str__(self):
        return f'{self.category}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    type = models.CharField(max_length=2, choices=TYPES, default=news)
    published_date = models.DateTimeField(auto_now_add=True)
    post_title = models.CharField(max_length=100)
    post_text = models.TextField()
    category = models.ManyToManyField(Category, through="PostCategory")
    post_rating = models.IntegerField(default=0)

    def categories(self):
        list = self.category.values_list().values_list('category', flat=True)
        return ('{}\n'*len(list)).format(*list)

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def preview(self):
        return self.post_text[:124] + "..."

    def __str__(self):
        return f'{self.post_title}'

    def get_absolute_url(self):
        if self.type == 'NW':
            return reverse('news_detail', args=[str(self.id)])
        elif self.type == 'AR':
            return reverse('article_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        cache.delete(f'post-{self.pk}')
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        cache.delete(f'post-{self.pk}')
        super().delete(*args, **kwargs)


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    comment_text = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_rating = models.IntegerField(default=0)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()


class Subscribers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

NewsPaper/sign/models.py
from django.db import models

# Create your models here.

NewsPaper/sign/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


"""
class BasicSignupForm(DefaultAccountAdapter):
    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        return user
"""


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Surname")

    class Meta:
        model = User
        fields = ("username",
                  "first_name",
                  "last_name",
                  "email",
                  "password1",
                  "password2", )

NewsPaper/sign/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User, Group
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from .forms import BaseRegisterForm
from newsportal.models import Author

from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from .tokens import account_activation_token


class AccountView(LoginRequiredMixin, TemplateView):
    template_name = 'sign/personal.html'


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        print(uid)
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(
            request, "Your email is confirmed. Account is activated.")
        return redirect('/sign/login/')
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect('/sign/login/')


def activateEmail(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string("account/email/email_confirmation_massage.html", {
        'user': user.username,
        'domain': get_current_site(request).domain + ':8000',
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Hello <b>{user}</b>, please go to you email <b>{to_email}</b> and click on \
                received activation link to confirm and complete the registration.')
    else:
        messages.error(
            request, f'Sending email to {to_email} failed, check if you typed it correctly.')


class BaseRegisterView(CreateView):
    model = User
    form_class = BaseRegisterForm
    success_url = '/sign/login/'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        activateEmail(self.request, user, form.cleaned_data['email'])
        return super().form_valid(form)

    """
    def form_valid(self, form):
        user = form.save(commit=False)
        try:
            return super().form_valid(form)
        finally:
            basic_group = Group.objects.get(name='common')
            basic_group.user_set.add(user)
    """


@login_required
def set_user_group_to_common(request):
    user = request.user
    common_group = Group.objects.get(name='common')
    if not request.user.groups.filter(name='common').exists():
        common_group.user_set.add(user)
    return redirect('/account/')


@login_required
def set_user_group_author(request):
    user_cur = request.user
    author_group = Group.objects.get(name='author')
    if not request.user.groups.filter(name='author').exists():
        author_group.user_set.add(user_cur)
    Author.objects.create(user=user_cur)
    return redirect('/account/')

NewsPaper/templates/sign/login.html
{% extends "flatpages/default.html" %}
{% load socialaccount %}

{% block view %}
<li class="nav-item">
    <a class="nav-link" href="/sign/signup/">Sign up</a>
</li>
{% endblock view %}
{% block account %}
{% endblock account %}
{% block blogout %}
{% endblock blogout %}

{% block content %}
<h2> Log in </h2>
<form method="post" action="{% url 'login' %}">
{% csrf_token %}

<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
    <td><p>&nbsp;</p><td>
</tr>
<tr>
    <td></td>
    <td><input type="submit" value="Enter"></td>
    <td><p>&nbsp;</p><td>
</tr>
<tr>
    <td>or</td>
    <td><a href="{% provider_login_url 'google' %}?next=/common/"> Log in with GOOGLE </a></td>
    <td><p>&nbsp;</p><td>
</tr>
<tr>
    <td>or</td>
    <td><a href="/sign/signup"> Sign up </a></td>
    <td><p>&nbsp;</p><td>
</tr>

</table>

</form>
{% endblock %}

NewsPaper/templates/sign/logout.html
{% extends "flatpages/default.html" %}

{% block view %}
<li class="nav-item">
    <a class="nav-link" href="/sign/login/">Log in</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="/sign/signup/">Sign up</a>
</li>
{% endblock view %}
{% block account %}
{% endblock account %}
{% block blogout %}
{% endblock blogout %}

{% block content %}
<h2> Logouted </h2>
{% endblock %}

NewsPaper/templates/sign/personal.html
<!DOCTYPE html>

{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Personal information
{% endblock title %}

{% block content %}
<h2>{{ post.post_title|censor }}</h2>
<hr>
<p style="text-align: left;"><em><strong>Username:</strong> {{ request.user.username }}</em></p>
<p style="text-align: left;"><em><strong>First name:</strong> {{ request.user.first_name }}</em></p>
<p style="text-align: left;"><em><strong>Surname:</strong> {{ request.user.last_name }}</em></p>
<p style="text-align: left;"><em><strong>Email:</strong> {{ request.user.email }}</em></p>
<p style="text-align: left;"><em><strong>Status</strong>:

    {% if request.user|has_group:"author" %}
    author
    {% else %}
    common
    <a class="nav-link" href="/sign/promote/">Promote to author</a>
    {% endif %}
    </em></p>
<p style="text-align: left;"><em><strong>Your subscriptions:</strong></em>
{% if request.user.category_set.all %}
{% for i in request.user.category_set.all %}
'{{ i }}'
{% endfor %} </p>
{% else %}
<p style="text-align: left;"><em>You are not subscribed to any of the categories yet.</em></p>
{% endif %}

{% endblock content%}

NewsPaper/templates/sign/signup.html
{% extends "flatpages/default.html" %}
{% block view %}
<li class="nav-item">
    <a class="nav-link" href="/sign/login/">Log in</a>
</li>
{% endblock view %}
{% block account %}
{% endblock account %}
{% block blogout %}
{% endblock blogout %}

{% block content %}

<form method="post">
{% csrf_token %}
    <p>
        <table style="height: 273px; width: 346px;">
            <tbody>
                <tr>
                    <td style="width: 146.562px; text-align: right;"></td>
                    <td style="width: 181.438px;"><h3> Singup </h3></td>
                </tr>
                <tr>
                    <td style="width: 146.562px; text-align: right;">username:</td>
                    <td style="width: 181.438px;">{{ form.username }}</td>
                </tr>
                <tr>
                    <td style="width: 146.562px; text-align: right;">first name:</td>
                    <td style="width: 181.438px;">{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td style="width: 146.562px; text-align: right;">surname:</td>
                    <td style="width: 181.438px;">{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td style="width: 146.562px; text-align: right;">email:</td>
                    <td style="width: 181.438px;">{{ form.email }}</td>
                </tr>
                <tr>
                    <td style="width: 146.562px; text-align: right;">password</td>
                    <td style="width: 181.438px;">{{ form.password1 }}</td>
                </tr>
                <tr>
                    <td style="width: 146.562px; text-align: right;">repeat password</td>
                    <td style="width: 181.438px;">{{ form.password2 }}</td>
                </tr>
                <tr>
                    <td style="width: 146.562px; text-align: right;"></td>
                    <td style="width: 181.438px;"><input type="submit" value="Продолжить"></td>
                </tr>
            </tbody>
        </table>
    </p>
</form>
{% endblock %}